### ISSUE TITLE
Data Collection for CPU

### ISSUE THREAD

**Issue by rohitagr0310** [Techie-AI/Primarily-Data#1]
Gather comprehensive data on various CPU models including specifications, performance metrics, and compatibility information.
**Tasks:**

- [x] Identify and list various CPU models.
- [x] Collect specifications and performance metrics.
- [ ] Gather compatibility information.
