### ISSUE TITLE
Finishing Touch for SSD

### ISSUE THREAD

**Issue by rohitagr0310** [Techie-AI/Primarily-Data#15]
Complete the SSD data preparation, ensuring it is deployment-ready and integrated into the chatbot.
**Tasks:**

- [ ] Review and finalize the SSD data sets.
- [ ] Ensure data is deployment-ready.
- [ ] Integrate data into the chatbot.
