### ISSUE TITLE
Data Collection for SSD

### ISSUE THREAD

**Issue by rohitagr0310** [Techie-AI/Primarily-Data#3]
Compile data on various SSD models covering aspects like capacity, speed, form factor, and compatibility.
**Tasks:**

- [x] Identify and list various SSD models.
- [x] Collect specifications including capacity, speed, and form factor.
- [ ] Gather compatibility information.
